### ISSUE TITLE
payment fails after accept call permission

### ISSUE THREAD

**Issue by omniashawkyabdallah** [born-ideas/masterpass-flutter-plugin#2]
I/Timeline(17567): Timeline: Activity_launch_request time:669838087 intent:Intent { cmp=com.refresh.juice/com.oltio.liblite.activity.LibLiteActivity (has extras) }
Timeline: Activity_launch_request time:669497851 intent:Intent { cmp=com.refresh.juice/com.oltio.liblite.activity.LibLiteActivity (has extras) }
W/ActivityThread(17567): handleWindowVisibility: no activity for token android.os.BinderProxy@209f4ab
W/System.err(17567): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
W/System.err(17567): 	at android.util.Base64.decode(Base64.java:118)
W/System.err(17567): 	at com.oltio.liblite.activity.LibLiteActivity.l(Unknown Source:50)
W/System.err(17567): 	at com.oltio.nix.a.f.a.a(Unknown Source:0)
W/System.err(17567): 	at com.oltio.nix.a.a.a(Unknown Source:4)
W/System.err(17567): 	at com.oltio.liblite.c.g$1.a(Unknown Source:4)
W/System.err(17567): 	at com.oltio.liblite.c.g$1.b(Unknown Source:0)
W/System.err(17567): 	at com.oltio.liblite.internal.h.a(Unknown Source:2)
W/System.err(17567): 	at com.oltio.liblite.internal.h.doInBackground(Unknown Source:2)
W/System.err(17567): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
W/System.err(17567): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(17567): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
W/System.err(17567): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(17567): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(17567): 	at java.lang.Thread.run(Thread.java:764)

**Comment by the-mars-rover** [comment]
Hi @omniashawkyabdallah - sorry for the late response but this plugin is no longer being actively supported. We recommend contacting Masterpass directly for the SDK details which can be used for implementing a new plugin.
